name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store  # Path to pnpm store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}  # Cache key includes pnpm-lock.yaml and package.json
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}  # Fallback key using pnpm-lock.yaml
            ${{ runner.os }}-pnpm-${{ runner.os }}  # Further fallback using the runner OS

      - name: Install Dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code for Tests
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "Running tests"

  build-and-push-docker-image:
    name: Build Docker Image and Push to Repositories
    runs-on: ubuntu-latest
    needs: [build, test-stage]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          tags: |
            karthickct/gitops-01:${{ github.sha }}
            ghcr.io/skarthickct/gitops-01:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=registry,ref=ghcr.io/skarthickct/gitops-01:latest

      - name: Output Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: [build-and-push-docker-image]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: skarthickct/gitops-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}

      - name: Setup git config
        run: |
          git config --global user.email "karthick@cloudthat.com"
          git config --global user.name "skarthickct"

      - name: Check current deployment.yaml contents
        run: cat deployment.yaml

      - name: Update Image in Deployment YAML
        run: |
          sed -i "s#image: .*#image: ghcr.io/skarthickct/gitops-01:${{ github.sha }}#g" deployment.yaml

      - name: Check for Changes in deployment.yaml
        id: check_changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes if Any
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git add deployment.yaml
          git commit -m "Update image to ghcr.io/skarthickct/gitops-01:${{ github.sha }}"
          git push origin master
