name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

  build-and-push-docker-image:
    name: Build Docker Image and Push to GHCR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/skarthickct/gitops-01:${{ github.sha }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Update Docker Cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - uses: actions/checkout@v3
        with:
          repository: skarthickct/gitops-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}

      - name: Setup git config
        run: |
          git config --global user.email "karthick@cloudthat.com"
          git config --global user.name "skarthickct"

      - name: Update Image in Deployment YAML
        run: |
          sed -i "s#image: .*#image: ghcr.io/skarthickct/gitops-01:${{ github.sha }}#g" deployment.yaml

      - name: Check for Changes in deployment.yaml
        id: check_changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes if Any
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git add deployment.yaml
          git commit -m "Update image to ghcr.io/skarthickct/gitops-01:${{ github.sha }}"
          git push origin master
