name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for faster checkout

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm' # Built-in pnpm caching

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Run Tests
        run: echo "Running tests" # Replace with actual test command if needed

      - name: Cache Build Output
        uses: actions/cache@v4
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore Build Cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GitHub Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/skarthickct/gitops-01:${{ github.sha }}
            ghcr.io/skarthickct/gitops-01:latest
          cache-from: type=registry,ref=ghcr.io/skarthickct/gitops-01:cache
          cache-to: type=inline

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - uses: actions/checkout@v4
        with:
          repository: skarthickct/gitops-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
          fetch-depth: 1

      - name: Setup git config
        run: |
          git config --global user.email "karthick@cloudthat.com"
          git config --global user.name "skarthickct"

      - name: Update Image in Deployment YAML
        run: |
          sed -i "s#image: .*#image: ghcr.io/skarthickct/gitops-01:${{ github.sha }}#g" deployment.yaml

      - name: Commit and Push Changes if Any
        run: |
          git add deployment.yaml
          git diff --cached --quiet || (git commit -m "Update image to ghcr.io/skarthickct/gitops-01:${{ github.sha }}" && git push origin master)
