name: CI Pipeline

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Build (Fast)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # speeds up checkout

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack (for pnpm)
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false  # we control install manually

      - name: Cache pnpm store
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build Project
        run: pnpm run build

  build-and-push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/skarthickct/gitops-01:${{ github.sha }}
            ghcr.io/skarthickct/gitops-01:latest
          cache-from: type=registry,ref=ghcr.io/skarthickct/gitops-01:latest
          cache-to: type=inline

  update-manifest-stage:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3
        with:
          repository: skarthickct/gitops-infra
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "karthick@cloudthat.com"
          git config --global user.name "skarthickct"

      - name: Update Image Tag in YAML
        run: |
          sed -i "s#image: .*#image: ghcr.io/skarthickct/gitops-01:${{ github.sha }}#g" deployment.yaml

      - name: Detect Changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_OUTPUT

      - name: Commit & Push Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git add deployment.yaml
          git commit -m "Update image to ghcr.io/skarthickct/gitops-01:${{ github.sha }}"
          git push origin master
